TARGET = vmsbackup

LIBS  = 
DEFS  = -DHAVE_STRERROR
DEFS += -D_LARGEFILE64_SOURCE
DEFS += -D_FILE_OFFSET_BITS=64
DEFS += -D_ISOC99_SOURCE
ifeq ($(HAVE_MTIO),1)
DEFS += -DHAVE_MTIO
endif

DEFS += $(EXTRA_DEFINES)
LIBS += $(EXTRA_LIBS)

EXE =
ifeq ($(MINGW),1)
	EXE = .exe
endif
ifeq ($(MSYS2),1)
	EXE = .exe
endif

WARNS = -Wall -ansi #-pedantic
CFLAGS = $(DEFS) $(HOST_MACH) $(OPT) $(DBG) $(WARNS) 
LFLAGS = $(HOST_MACH)
ifeq ($(HAVE_MTIO),1)
LIBS += -lrmt   			# remote magtape library
endif

ifndef NO_CP_TAPE
ALSO_CP_TAPE = cp_tape$(EXE)
endif
ifndef NO_UNPACK_TAP
ALSO_UNPACK_TAP = unpack_tap$(EXE)
endif

#OWNER = tar			# user for remote tape access
#MODE = 4755
#BINDIR = /usr/local/bin
#MANSEC = l
#MANDIR = /usr/man/man$(MANSEC)

#

default: vmsbackup$(EXE) dmp_tfile$(EXE) ext_tfile$(EXE) $(ALSO_CP_TAPE) $(ALSO_UNPACK_TAP) libvmsbackup.a

%.o : %.c Makefile.common
	$(CC) -c $(CFLAGS) $<

vmsbackup_nom.o: vmsbackup.c Makefile.common
	$(CC) -c $(CFLAGS) -DVMSBACKUP_NO_MAIN -o $@ $<

libvmsbackup.a: vmsbackup_nom.o match.o
	$(AR) rcs $@ $^

vmsbackup$(EXE): vmsbackup.o match.o
	$(CC) $(LFLAGS) -o $@ $^
cp_tape$(EXE): cp_tape.o
	$(CC) $(LFLAGS) -o $@ $<
dmp_tfile$(EXE): dmp_tfile.o
	$(CC) $(LFLAGS) -o $@ $<
ext_tfile$(EXE): ext_tfile.o
	$(CC) $(LFLAGS) -o $@ $<
unpack_tap$(EXE): unpack_tap.o
	$(CC) $(LFLAGS) -o $@ $<

#install:
#	install -m $(MODE) -o $(OWNER) -s vmsbackup $(BINDIR)	
#	cp vmsbackup.1 $(MANDIR)/vmsbackup.$(MANSEC)
clean:
	$(RM) vmsbackup$(EXE) ext_tfile$(EXE) cp_tape$(EXE) dmp_tfile$(EXE) unpack_tap$(EXE) libvmsbackup.a vmsbackup_nom.o *.o core

#shar:
#	shar -a README vmsbackup.1 Makefile vmsbackup.c match.c \
#	    > vmsbackup.shar
